---
title: "Introduction to Data Frames in R"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
#load libraries
library(dplyr)
library(readr)
```
```{r}
artists <- read.csv('artists.csv')
```
```{r}
#inspect data frame
artists
head(artists)
summary(artists)
```
```{r}
#inspect data frame with pipe
artists %>%
  head()
```
```{r}
#select one column
artist_groups <- select(artists,group)
```

```{r}
#select multiple column
group_info <- select(artists,group,spotify_monthly_listeners,year_founded)
```

```{r}
# select all columns except one
no_albums <- select(artists,-albums)
```

```{r}
# select all columns except a set
df_cols_removed <- select(artists, -genre, -spotify_monthly_listeners, -year_founded)
```

```{r}
#filter rows one condition
rock_groups <- artists %>% filter(genre == 'Rock')
print(rock_groups)
```

```{r}
#filter rows multiple conditions
popular_rock_groups <- artists %>% filter(genre == 'Rock', spotify_monthly_listeners >= 20000000)
print(popular_rock_groups)
```
```{r}
# filter rows with or
korea_or_before_2000 <- artists %>% filter(country == 'South Korea' | year_founded < 2000)
print(korea_or_before_2000)
```
```{r}
# filter rows with not !
not_rock_groups <- artists %>% filter(!(genre == 'Rock'))
print(not_rock_groups)
```
```{r}
# arrange rows in ascending order
group_asc <- artists %>% arrange(group)
print(group_asc)
```
```{r}
# arrange rows in descending order
youtube_desc <- artists %>% arrange(desc(youtube_subscribers))
print(youtube_desc)
```

