---
title: "Median in R"
output: html_notebook
---
```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)

# Array of the first five author ages
five_author_ages <- c(29, 49, 42, 43, 32)

# Fill in the empty array with the values sorted
sorted_author_ages <- c(29, 32, 42, 43, 49)

# Save the median value to median_value
median_value <- 42

# Print the sorted array and median value
cat("The sorted array is:", sorted_author_ages)
cat(paste("The median of the array is: ", median_value))
```

```{r}
# Load data frame
greatest_books <- read_csv('top-hundred-books.csv')


# Save author ages to author_ages
author_ages <- greatest_books$Ages

# Use R to calculate the median age of the top 100 authors
median_age <- median(author_ages)

print(paste("The median age of the 100 greatest authors, according to a survey by Le Monde is: " , median_age))
```
how to find the median of a dataset in two steps:

1. Sort the dataset
2. Identify the one or two numbers that fall in the middle of the sorted dataset
