---
title: "Quartiles"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(ggplot2)
```

```{r}
# load song data
load("songs.Rda")
```

```{r message=FALSE}
# plot histogram
hist <- qplot(songs,
              geom="histogram",
              main = 'Histogram of Song Lengths',
              xlab = 'Song Length (Seconds)',
              ylab = 'Count',
              fill=I("blue"),
              col=I("red"),
              alpha=I(.2)) +
        geom_vline(aes(xintercept=quantile(songs,0.25),
                       color=I("blue")),
                   linetype="solid",
                   size=1,
                   show.legend=T) +
				geom_vline(aes(xintercept=quantile(songs,0.5),
                       color=I("purple")),
                   linetype="solid",
                   size=1,
                   show.legend=T) +
  			geom_vline(aes(xintercept=quantile(songs,0.75),
                       color=I("yellow")),
                   linetype="solid",
                   size=1,
                   show.legend=T) + 
				scale_colour_manual(name = "",
                            labels =c("Q1","Q2","Q3"),
                            values=c("blue","purple","yellow"))

hist
```